-- 코드를 입력하세요
SELECT usb.TITLE, usb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') 
FROM USED_GOODS_BOARD usb
JOIN USED_GOODS_REPLY ugr USING (BOARD_ID)
WHERE YEAR(usb.CREATED_DATE) = 2022 
AND MONTH(usb.CREATED_DATE) = 10
ORDER BY ugr.CREATED_DATE ASC, usb.TITLE ASC;